### ISSUE TITLE
deal with non-english vegetables

### ISSUE THREAD

**Issue by dmil** [code4policy/bad-veggies-website-section-a#10]
What language even is that? What does it say? 

![image](https://user-images.githubusercontent.com/468544/101128232-2fb6a980-35cd-11eb-959d-187eb32119e8.png)

Should we delete it or convert it?

**Comment by Leo-Bol** [comment]
What about deleting the item? That would solve the issue

**Comment by sshaffer-hks** [comment]
Would this leave an important item out of the table? I WISH I KNEW

**Comment by Leo-Bol** [comment]
What about google translating it? And then deciding about toss/keep?

**Comment by sshaffer-hks** [comment]
I think that's a great start!!
