### ISSUE TITLE
add a paragraph about fruits

### ISSUE THREAD

**Issue by dmil** [code4policy/bad-veggies-website-section-a#17]

**Comment by yaelabadi** [comment]
Edit

**Comment by jordancallahan** [comment]
Agreed, a paragraph about fruits is missing. Would be useful to include some information on the fruits from the table.

**Comment by fhenry551** [comment]
Yes, agreed, we should include a paragraph about fruits.

**Comment by jordancallahan** [comment]
Paragraph on fruits has been added, PR'd, and merged into main.
