### ISSUE TITLE
remove gym socks from table

### ISSUE THREAD

**Issue by dmil** [code4policy/bad-veggies-website-section-a#7]
Hey! Gym socks are not a vegetable. This ticket is about removing them from the table. Should we remove them or replace them with a vegetable? 

Don't remove the paragraph about gym socks yet though...that's a separate ticket (#22). This ticket is only about the table.

**Comment by nkhlgeorge** [comment]
But I think gym socks are a pressing issue to address

**Comment by ranimurali671** [comment]
I agree we should remove gym socks. I think they should be replaced with another vegetable! There are a lot of other vegetables not included in the table.

**Comment by vicyingc** [comment]
how about replacing gym socks with sweet potato? They are yummy!

**Comment by YFolathi** [comment]
it's a total turn off!
